builds:
  - id: default
    goos:
      - linux
      - windows
    goarch:
      - amd64
  - id: macos
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post: ./gon.sh {{.Path}} {{dir (dir .Path)}}/{{.ProjectName}}_{{.Version}}_{{.Target}}.zip
archives:
  - builds:
      - default
    format_overrides:
      - goos: windows
        format: zip
release:
  ids:
    - default
  extra_files:
    - glob: ./dist/*_darwin_*.zip
