on:
  push:
    tags:
      - 'v*'
name: release
jobs:
  release:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Install gon
      run: |-
        brew tap mitchellh/gon
        brew install mitchellh/gon/gon
    - name: Import certificates
      uses: Apple-Actions/import-codesign-certs@v1.0.4
      with:
        p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE }}
        p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
    - name: goreleaser
      uses: goreleaser/goreleaser-action@v4.6.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AC_PASSWORD: ${{ secrets.AC_PASSWORD }}