
on: [push, pull_request]
name: tests
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test -v ./...