
on: [push, pull_request]
name: tests
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2.4.0
    - name: Test
      run: go test -v ./...