
on: [push, pull_request]
name: tests
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install keyring packages
      # https://github.com/99designs/keyring/blob/c2a5408c4d2916c865785523eb98d4e6c1f62611/.github/workflows/ci.yml
      run: sudo apt-get install pass gnome-keyring dbus-x11
    - name: Test
      run: go test -v ./...