
on:
  push:
    branches:
      - master
  pull_request:
name: tests
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Test
      run: go test -v ./...
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Install keyring packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gnome-keyring dbus-x11 libsecret-1-dev
    - name: Setup keyring directories
      run: |
        mkdir -p ~/.cache
        mkdir -p ~/.local/share/keyrings
        chmod 700 ~/.local
    - name: Test with keyring
      run: |
        echo 'test-passphrase' | gnome-keyring-daemon --unlock
        go test -v ./...
      shell: dbus-run-session -- bash --noprofile --norc -eo pipefail {0}
